### ISSUE TITLE
Trying to `show` any story results in error

### ISSUE THREAD

**Issue by benekastah** [tubbo/pv#3]
``` bash
$ pv show 53846349                                                                                                                                                                                                 [1.9.2-p320]
/Users/paulh/Library/Ruby/Gems/1.8/gems/pv-0.0.9.1/lib/pv/command.rb:18:in `show': undefined method `write' for File:Class (NoMethodError)
        from /Users/paulh/Library/Ruby/Gems/1.8/gems/thor-0.18.1/lib/thor/command.rb:27:in `run'
        from /Users/paulh/Library/Ruby/Gems/1.8/gems/thor-0.18.1/lib/thor/invocation.rb:120:in `invoke_command'
        from /Users/paulh/Library/Ruby/Gems/1.8/gems/thor-0.18.1/lib/thor.rb:363:in `dispatch'
        from /Users/paulh/Library/Ruby/Gems/1.8/gems/thor-0.18.1/lib/thor/base.rb:439:in `start'
        from /Users/paulh/Library/Ruby/Gems/1.8/gems/pv-0.0.9.1/bin/pv:7:in `<top (required)>'
        from /Users/paulh/Library/Ruby/Gems/1.8/bin/pv:23:in `load'
        from /Users/paulh/Library/Ruby/Gems/1.8/bin/pv:23:in `<main>'
```

**Comment by zph** [comment]
Hi @benekastah,

That's an error because the command is installed using a deprecated version of Ruby.  The `File.write` method doesn't exist in Ruby 1.8.

You can try using the RVM project or Rbenv project for easily installing a more current version of Ruby than OSX comes with.
